<?php
/**
 * ItemVendorDetailsByMarketplaceTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Ced
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ced\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ItemVendorDetailsByMarketplaceTest Class Doc Comment
 *
 * @category    Class
 * @description Vendor details associated with an Amazon catalog item for the indicated Amazon marketplace.
 * @package     Ced
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ItemVendorDetailsByMarketplaceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ItemVendorDetailsByMarketplace"
     */
    public function testItemVendorDetailsByMarketplace()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "marketplace_id"
     */
    public function testPropertyMarketplaceId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "brand_code"
     */
    public function testPropertyBrandCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "manufacturer_code"
     */
    public function testPropertyManufacturerCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "manufacturer_code_parent"
     */
    public function testPropertyManufacturerCodeParent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_category"
     */
    public function testPropertyProductCategory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_group"
     */
    public function testPropertyProductGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_subcategory"
     */
    public function testPropertyProductSubcategory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replenishment_category"
     */
    public function testPropertyReplenishmentCategory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
