<?php
/**
 * FbaOutboundApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Ced
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Ced\Test\Api;

use \Ced\Configuration;
use \Ced\ApiException;
use \Ced\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FbaOutboundApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ced
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FbaOutboundApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelFulfillmentOrder
     *
     * .
     *
     */
    public function testCancelFulfillmentOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createFulfillmentOrder
     *
     * .
     *
     */
    public function testCreateFulfillmentOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createFulfillmentReturn
     *
     * .
     *
     */
    public function testCreateFulfillmentReturn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFeatureInventory
     *
     * .
     *
     */
    public function testGetFeatureInventory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFeatureSKU
     *
     * .
     *
     */
    public function testGetFeatureSKU()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFeatures
     *
     * .
     *
     */
    public function testGetFeatures()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFulfillmentOrder
     *
     * .
     *
     */
    public function testGetFulfillmentOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFulfillmentPreview
     *
     * .
     *
     */
    public function testGetFulfillmentPreview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPackageTrackingDetails
     *
     * .
     *
     */
    public function testGetPackageTrackingDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAllFulfillmentOrders
     *
     * .
     *
     */
    public function testListAllFulfillmentOrders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listReturnReasonCodes
     *
     * .
     *
     */
    public function testListReturnReasonCodes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateFulfillmentOrder
     *
     * .
     *
     */
    public function testUpdateFulfillmentOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
